-- ============================================
-- Migration 010: Add Demo Mode for LLM Partner Simulation
-- ============================================
-- Adds demo_mode flag to messaging preferences
-- When enabled, partner_b is simulated by an LLM

-- Add demo_mode column to partner_messaging_preferences
ALTER TABLE partner_messaging_preferences
ADD COLUMN IF NOT EXISTS demo_mode_enabled BOOLEAN DEFAULT false;

-- Add comment for documentation
COMMENT ON COLUMN partner_messaging_preferences.demo_mode_enabled IS
'When true, partner_b responses are generated by an LLM using their onboarding profile';
